### ISSUE TITLE
hard-coded lang

### ISSUE THREAD

**Issue by danmarsden** [SaseTRT15/certrt#4]
this page includes some hard-coded text that should sit within the lang pack:
https://github.com/SaseTRT15/certrt/blob/master/pdfpreview.php#L30

I couldn't see any others that needed changing but I didn't look through all your code.

**Comment by vmfvmf** [comment]
I just found one, the others are parameters derived from components ids these should be in lang pack too?

I think not, but, if its a pre-requisite, then we can edit.
